global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "delay-service"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["192.168.101.92:8888"]
  - job_name: "spring-mvc"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["192.168.101.239:8080"]
  - job_name: "delay-spring-flux"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["192.168.101.140:8080"]
  - job_name: "vertx"
    scrape_interval: 5s
    static_configs:
      - targets: [ "192.168.101.27:8080" ]
  - job_name: "vertx-coroutine"
    scrape_interval: 5s
    static_configs:
      - targets: [ "192.168.101.210:8080" ]
  - job_name: "ktor"
    scrape_interval: 5s
    static_configs:
      - targets: [ "192.168.101.114:8080" ]
